# Generated by Django 5.1.1 on 2024-11-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otc_bond',
            options={'managed': False},
        ),
    ]
