# Generated by Django 5.1.1 on 2024-12-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0002_otcbondtrending_bond_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otc_bond_interest',
            table='OTC_Bond_Interest',
        ),
    ]
