# Generated by Django 5.1.1 on 2024-11-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_OtcBond', '0002_alter_otc_bond_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otc_bond',
            table='crawling_otc_bond',
        ),
    ]
