# Generated by Django 5.1.1 on 2024-11-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('usr', '0003_alter_users_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.searchkeyword')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.users')),
            ],
            options={
                'unique_together': {('search_keyword', 'user_id')},
            },
        ),
    ]
