# Generated by Django 5.1.1 on 2024-12-12 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewskeyword',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='navernews',
            constraint=models.UniqueConstraint(fields=('originallink',), name='unique_naver_news'),
        ),
        migrations.AlterUniqueTogether(
            name='usernewskeyword',
            unique_together={('search_keyword', 'user_id')},
        ),
    ]
