# Generated by Django 5.1.1 on 2024-11-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_rename_user_pk_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
