# Generated by Django 5.1.1 on 2024-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="searchkeyword",
            constraint=models.UniqueConstraint(
                fields=("search_keyword",), name="unique_keyword"
            ),
        ),
    ]
