# Generated by Django 5.1.1 on 2024-11-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketbond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ET_Bond_Expired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_bonds', to='marketbond.marketbondcode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_bonds', to='marketbond.users')),
            ],
            options={
                'db_table': 'ET_Bond_Expired',
            },
        ),
        migrations.CreateModel(
            name='EtBondPreDataDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_set', to='marketbond.marketbondcode')),
            ],
            options={
                'db_table': 'EtBondPreData',
            },
        ),
        migrations.CreateModel(
            name='EtBondPreDataMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_months_set', to='marketbond.marketbondcode')),
            ],
            options={
                'db_table': 'EtBondPreDataMonths',
            },
        ),
        migrations.CreateModel(
            name='EtBondPreDataWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_data_weeks_set', to='marketbond.marketbondcode')),
            ],
            options={
                'db_table': 'EtBondPreDataWeeks',
            },
        ),
        migrations.CreateModel(
            name='ET_Bond_Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_10', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('purchase_date', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_bonds', to='marketbond.marketbondcode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_bonds', to='marketbond.users')),
            ],
            options={
                'db_table': 'ET_Bond_Holding',
                'unique_together': {('user_id', 'bond_code')},
            },
        ),
        migrations.CreateModel(
            name='ET_Bond_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketbond.marketbondcode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketbond.users')),
            ],
            options={
                'unique_together': {('user_id', 'bond_code')},
            },
        ),
    ]
