# Generated by Django 5.1.1 on 2024-11-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketbond', '0002_users_et_bond_expired_etbondpredatadays_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='et_bond_interest',
            table='ET_Bond_Interest',
        ),
    ]
