# Generated by Django 5.1.1 on 2024-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketbond', '0003_marketbondtrending_bond_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='et_bond_holding',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
