# Generated by Django 5.1.1 on 2024-11-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketbond', '0003_alter_et_bond_interest_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='et_bond_holding',
            unique_together={('user_id', 'bond_code', 'price_per_10')},
        ),
    ]
