# Generated by Django 5.1.1 on 2024-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketbond', '0004_alter_et_bond_holding_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBondPreDataDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MarketBondPreDataDays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBondPreDataMonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MarketBondPreDataMonths',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBondPreDataWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MarketBondPreDataWeeks',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='etbondpredatamonths',
            name='bond_code',
        ),
        migrations.RemoveField(
            model_name='etbondpredataweeks',
            name='bond_code',
        ),
        migrations.DeleteModel(
            name='EtBondPreDataDays',
        ),
        migrations.DeleteModel(
            name='EtBondPreDataMonths',
        ),
        migrations.DeleteModel(
            name='EtBondPreDataWeeks',
        ),
    ]
