# Generated by Django 5.1.1 on 2024-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usr", "0002_alter_users_managers_users_date_joined_users_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(default="", max_length=150),
        ),
    ]
