# Generated by Django 5.1.1 on 2024-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0003_alter_otc_bond_interest_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="otc_bond_holding",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
