# Generated by Django 5.1.1 on 2024-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawling", "0012_otcbondpredatamonths_otcbondpredataweeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otc_bond",
            name="add_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
