# Generated by Django 5.1.1 on 2024-11-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketbond", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketBondPreDataDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_date", models.DateField(auto_now_add=True)),
                ("duration", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
            ],
            options={
                "db_table": "MarketBondPreDataDays",
            },
        ),
        migrations.CreateModel(
            name="MarketBondPreDataMonths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_date", models.DateField(auto_now_add=True)),
                ("duration", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
            ],
            options={
                "db_table": "MarketBondPreDataMonths",
            },
        ),
        migrations.CreateModel(
            name="MarketBondPreDataWeeks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_date", models.DateField(auto_now_add=True)),
                ("duration", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
            ],
            options={
                "db_table": "MarketBondPreDataWeeks",
            },
        ),
    ]
