# Generated by Django 5.1.1 on 2024-12-02 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketbond", "0003_marketbondtrending_bond_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ET_Bond_Expired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ET_Bond_Expired",
            },
        ),
        migrations.CreateModel(
            name="ET_Bond_Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_per_10", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("purchase_date", models.CharField(max_length=100)),
                ("expire_date", models.DateField()),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ET_Bond_Holding",
                "unique_together": {("user_id", "bond_code", "price_per_10")},
            },
        ),
        migrations.CreateModel(
            name="ET_Bond_Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bond_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketbond.marketbondcode",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ET_Bond_Interest",
                "unique_together": {("user_id", "bond_code")},
            },
        ),
    ]
