# Generated by Django 5.1.1 on 2024-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketbond", "0004_et_bond_expired_et_bond_holding_et_bond_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="et_bond_holding",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
