# Generated by Django 5.1.1 on 2024-12-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketbond", "0004_et_bond_expired_et_bond_holding_et_bond_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketbondcmb",
            name="code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketbond.marketbondcode",
            ),
        ),
    ]
